// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmIAS6W0d03_rRb4GKiZkZTKwV8dl04Fg',
    appId: '1:287797696653:web:41469f40e980fb5e38aac4',
    messagingSenderId: '287797696653',
    projectId: 'fir-phonauth',
    authDomain: 'fir-phonauth.firebaseapp.com',
    storageBucket: 'fir-phonauth.appspot.com',
    measurementId: 'G-F3JZZHXN8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPYCahdqyh4-lo-OwNrNTa7ST68bNzXg',
    appId: '1:287797696653:android:5e713bf99843796638aac4',
    messagingSenderId: '287797696653',
    projectId: 'fir-phonauth',
    storageBucket: 'fir-phonauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR8V-F3OswKVTKnE7VGMzh3riNK_16Ulg',
    appId: '1:287797696653:ios:8cfd162a5cebafa538aac4',
    messagingSenderId: '287797696653',
    projectId: 'fir-phonauth',
    storageBucket: 'fir-phonauth.appspot.com',
    iosClientId: '287797696653-h4rk5lqv3f2017d2h4iivv0biugrgkc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthPhoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR8V-F3OswKVTKnE7VGMzh3riNK_16Ulg',
    appId: '1:287797696653:ios:8cfd162a5cebafa538aac4',
    messagingSenderId: '287797696653',
    projectId: 'fir-phonauth',
    storageBucket: 'fir-phonauth.appspot.com',
    iosClientId: '287797696653-h4rk5lqv3f2017d2h4iivv0biugrgkc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthPhoneAuth',
  );
}
